# Generated by Django 4.1 on 2022-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimgs',
            name='images',
            field=models.CharField(max_length=400),
        ),
    ]
