# Generated by Django 4.1 on 2022-08-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postimgs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimgs',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post'),
        ),
    ]
