# Generated by Django 4.1 on 2022-08-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postimgs_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimgs',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='post.post'),
        ),
    ]
