# Generated by Django 4.1 on 2022-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_postimgs_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.related.ForeignKey><djangodbmodelsfieldsDateTimeField>', unique=True),
        ),
    ]
