# Generated by Django 4.1 on 2022-08-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_post_created_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
