# Generated by Django 4.1 on 2022-08-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimgs',
            old_name='images',
            new_name='image',
        ),
    ]
