# Generated by Django 4.1 on 2022-08-15 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.FloatField(blank=True, max_length=9999999999, null=True, unique=True)),
                ('profile_image', models.ImageField(upload_to='')),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=user.models.UserExtend.defaultSlug, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
