# Generated by Django 4.1 on 2022-08-15 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phone_number',
            field=models.FloatField(blank=True, max_length=9999999999, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
