# Generated by Django 4.1 on 2022-08-17 01:10

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userextend_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phone_number',
            field=models.FloatField(blank=True, max_length=9999999999, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Please write a valid number')]),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='profile_image',
            field=models.ImageField(upload_to=user.models.profile_img),
        ),
    ]
