# Generated by Django 4.1 on 2022-08-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='name',
        ),
    ]
