# Generated by Django 4.1 on 2022-08-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userextend_last_name_remove_userextend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
