# Generated by Django 4.1 on 2022-08-20 23:08

from django.conf import settings
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_userextend_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.profile_img),
        ),
    ]
