# Generated by Django 4.1 on 2022-08-23 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userextend_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phone_number',
            field=models.FloatField(blank=True, max_length=9999999999, null=True, unique=True, validators=[django.core.validators.RegexValidator('[0-9]{10}$', 'Please write a valid number')]),
        ),
    ]
