# Generated by Django 4.1 on 2022-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userextend_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phone_number',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
