# Generated by Django 4.1 on 2022-08-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userextend_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followers',
        ),
    ]
