# Generated by Django 4.1 on 2022-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
